export * from './camionController.service';
import { CamionControllerService } from './camionController.service';
export * from './chargementController.service';
import { ChargementControllerService } from './chargementController.service';
export * from './chauffeurController.service';
import { ChauffeurControllerService } from './chauffeurController.service';
export * from './clientController.service';
import { ClientControllerService } from './clientController.service';
export * from './dechargementController.service';
import { DechargementControllerService } from './dechargementController.service';
export * from './declarationController.service';
import { DeclarationControllerService } from './declarationController.service';
export * from './depotController.service';
import { DepotControllerService } from './depotController.service';
export * from './projetClientController.service';
import { ProjetClientControllerService } from './projetClientController.service';
export * from './projetDepotController.service';
import { ProjetDepotControllerService } from './projetDepotController.service';
export * from './projetController.service';
import { ProjetControllerService } from './projetController.service';
export * from './societeController.service';
import { SocieteControllerService } from './societeController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './voyageController.service';
import { VoyageControllerService } from './voyageController.service';
export const APIS = [CamionControllerService, ChargementControllerService, ChauffeurControllerService, ClientControllerService, DechargementControllerService, DeclarationControllerService, DepotControllerService, ProjetClientControllerService, ProjetDepotControllerService, ProjetControllerService, SocieteControllerService, UserControllerService, VoyageControllerService];
