/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Chargement DTO
 */
export interface ChargementDTO { 
    id?: number;
    camionId: number;
    chauffeurId: number;
    societe: string;
    societeP?: string;
    projetId: number;
    nomProjet?: string;
    produit?: string;
    navire?: string;
    port?: string;
    dateChargement: string;
}
