/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChauffeurDTO { 
    id?: number;
    nom: string;
    numCin: string;
    numBonLivraisonVoyages?: Set<string>;
}

