/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Dechargement DTO
 */
export interface DechargementDTO { 
    id?: number;
    chargementId: number;
    numTicket?: string;
    numBonLivraison?: string;
    poidCamionVide?: number;
    poidComplet?: number;
    clientId: number;
    depotId: number;
    dateDechargement?: string;
    
    // Données du chargement (lecture seule)
    camionId?: number;
    chauffeurId?: number;
    societe?: string;
    projetId?: number;
    nomProjet?: string;
    produit?: string;
    navire?: string;
    port?: string;
    dateChargement?: string;
}
