/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeclarationDTO { 
    id?: number;
    numeroDeclaration: string;
    quantiteManifestee: number;
    projetId: number;
    projetNom?: string;
}
