/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DepotDTO { 
    id?: number;
    nom?: string;
    adresse?: string;
    mf?: string;
    projetId?: number;
}

