export * from './camionDTO';
export * from './chauffeurDTO';
export * from './clientDTO';
export * from './declarationDTO';
export * from './depotDTO';
export * from './loginDTO';
export * from './projetClientDTO';
export * from './projetDTO';
export * from './voyageDTO';
