/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjetDTO { 
    id?: number;
    nomProduit: string;
    quantiteTotale: number;
    nomNavire: string;
    paysNavire: string;
    etat: string;
    port?: string;
    dateDebut?: string;
    dateFin?: string;
    active?: boolean;
    // Compatibilité: backend expose aussi les sociétés complètes
    societes?: Array<import('./societeDTO').SocieteDTO>;
    societeNoms?: Set<string>;
}

