/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjetDTO { 
    id?: number;
    nom: string;
    nomProduit: string;
    quantiteTotale: number;
    nomNavire: string;
    paysNavire: string;
    etat: string;
}

