/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjetClientDTO { 
    id?: number;
    projetId?: number;
    clientId?: number;
    quantiteAutorisee?: number;
}

