/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SocieteDTO { 
    id?: number;
    nom: string;
    adresse?: string;
    rcs?: string;
    contact?: string; // JSON string of phone numbers
    tva?: string;
}
