/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VoyageDTO { 
    id?: number;
    numBonLivraison?: string;
    numTicket?: string;
    reste?: number;
    date?: string;
    poidsClient?: number;
    poidsDepot?: number;
    chauffeurIds?: Set<number>;
    camionIds?: Set<number>;
    clientId?: number;
    depotId?: number;
    projetId?: number;
}

