/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VoyageDTO { 
    id?: number;
    numBonLivraison?: string;
    numTicket?: string;
    reste?: number;
    date?: string;
    poidsClient?: number;
    poidsDepot?: number;
    chauffeurId?: number;
    chauffeurNom?: string;
    camionId?: number;
    camionNom?: string;
    clientId?: number;
    clientNum?: string;
    depotId?: number;
    depotNom?: string;
    projetId?: number;
    userId?: number;
}

